Repository ynput/ayon-launcher, pull requests merged in 2025-04, with the labels that each got.

#209 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  poetry.lock
  pyproject.toml
Labels: type: feature

#212 Remove forced pip update
  tools/make.sh
Labels: type: bug

#213 Chore: Allow to skip or block auto update
  README.md
  common/ayon_common/distribution/__init__.py
  common/ayon_common/distribution/utils.py
  start.py
Labels: type: enhancement

#210 Chore: Autoupdater can handle shared distribution paths
  common/ayon_common/distribution/__init__.py
  common/ayon_common/distribution/control.py
  common/ayon_common/distribution/tests/test_addon_distribution.py
  common/ayon_common/distribution/utils.py
  start.py
Labels: type: enhancement

#215 Chore: Fix attribute error in Installer
  common/ayon_common/distribution/data_structures.py
Labels: type: bug

#216 Chore: Update ayon api
  poetry.lock
  pyproject.toml
Labels: type: enhancement

#217 Distribution: Unzipped content move is guarded
  common/ayon_common/distribution/control.py
Labels: type: enhancement

#218 Chore: Revert dependencies for docs build
  poetry.lock
  pyproject.toml
Labels: type: bug
